services:
  log-exporter:
    environment:
      READ_LOCATION: ${READ_LOCATION}
      BUFFER_SIZE: ${BUFFER_SIZE}
    build:
     context: .
     dockerfile: Dockerfile
    ports:
    - "127.0.0.1:8000:8000"
    volumes:
      - /var/log/:${READ_LOCATION}:ro
volumes:
  logs:
    