services:
  log-exporter:
    environment:
      READ_LOCATION: "/logs"
      BUFFER_SIZE: 8192
    build:
     context: .
     dockerfile: Dockerfile
    ports:
    - "127.0.0.1:8000:8000"
    volumes:
      - /var/log/:/logs:ro
volumes:
  logs:
    